### ISSUE TITLE
Adding support for objects with indexers

### ISSUE THREAD

**Issue by jzarob** [castle-it/dynamic-linq-query-builder#10]
I wanted to utilize your package to support objects with indexers. However, I want to make sure that I implement the change in the most correct way possible.

I'd first modify the `BuildQuery<T>` methods to add 2 optional parameters, `useIndexedProperty = false` and `indexedPropertyName = null`, to avoid forcing code changes to existing projects that reference this package.

`BuildExpressionTree` would also need to be modified to accept these two parameters, and then change [QueryBuilder.cs L154](https://github.com/castle-it/dynamic-linq-query-builder/blob/master/Castle.DynamicLinqQueryBuilder/QueryBuilder.cs#L154) to read:

```csharp
Expression propertyExp = usedIndexedProperty ? Expression.Property(pe, indexedPropertyName, Expression.Constant(rule.Field))
    : Expression.Property(pe, rule.Field);
```

This doesn't have to be implemented in the main repo, as I can fork it and implement it myself, however if this is a feature you'd want implemented in the main repository, I'd be glad to do it, just want to make sure the design is right.

Thanks for your awesome repo!

**Comment by tghamm** [comment]
Hey there,
Thanks for your interest!

I think we'd welcome that as a PR if you're interested in putting it together.  In fact, I've already done something pretty similar in a private fork (it's less generic, and therefore not implemented in the main repo), but the addition to the main repo would be nice.

My only thought would be to perhaps add additional `BuildQuery<T>` signatures that accept your additional parameters instead of optional parameters on the existing signatures.  That's really just a preference though.

Let me know if I can be of any help along the way, and thanks again for taking an interest!
