### ISSUE TITLE
Set CSV file as Source for Castle Linq Builder

### ISSUE THREAD

**Issue by weedkiller** [castle-it/dynamic-linq-query-builder#28]
Hi, 

- how can we set the data source as CSV file.
- Also how can I get/save the user Linq query

**Comment by tghamm** [comment]
@weedkiller you've got a couple of options:

For your first item:
Since this library works against any in-memory data set, I'd just use whatever library you like to parse and read the contents of the csv file into memory and then execute the query against that List of objects.

For your second:
Saving the compiled query is tricky.  The next release, 1.1.1 will support re-using a predicate formed by the library for improved performance with repeated queries.  However, I'm not sure it can be practically serialized for permanent storage and recalled.  You may simple need to serialize and store the `FilterRule` and rebuild the query on every use if permanent storage is required.

**Comment by weedkiller** [comment]
thanks @tghamm how can we append or modify the query in code. For e.g. if I want to switch a sum to count is that possible, how would i modify the query itself using your lib

**Comment by tghamm** [comment]
So, you've got a few options:

You can manually adjust the `FilterRule` collection before it's compiled into a predicate, you can also chain `Where(...)` on the end of the query e.g `collection.BuildQuery(filterRules).Where(p => p.Something == 12)`.

Sums and counts aren't part of this library directly, it's just responsible for the `Where` part of the query, so you can still yourself easily `Select` a property and call `Sum` or just a `Count()` of the collection and chain it onto `BuildQuery`.

**Comment by tghamm** [comment]
@weedkiller the object produced by this library is an `IQueryable`, so you can append any linq you need:
```csharp
var resultQueryable = myCollection.BuildQuery(filters);
var result = 0.0;
if (options.average) {
   result = resultQueryable.Select(p => p.Price).Average();
} else {
   result = resultQueryable.Select(p => p.Price).Sum();
}
```

Basically something along those lines.  What you're asking about technically falls outside of the scope of this library, but there are other libraries that allow selection of properties by name, e.g. `Select("Price")`, and switching between average and sum should be fairly trivial at the end.

This library is for the `Where` portion of the query, not aggregation and selection.
