### ISSUE TITLE
Question: ColumnDefinition Select Input Values

### ISSUE THREAD

**Issue by GhostA08** [castle-it/dynamic-linq-query-builder#36]
In jQuery QueryBuilder (https://querybuilder.js.org/) it list "Available types are text, number, textarea, radio, checkbox and select." as valid options for inputting values into the UI.  I have fields that I would like to use the select input on but can not seem to get the right values or format to the right properties. Does dynamic-linq-query-builder support using the select input and if so are there any example source code it can look at?

**Comment by tghamm** [comment]
@GhostA08 dynamic-linq-query-builder should still support the format of the `FilterRule` that's built based off of those types, but the convenience implementation we have for `ColumnDefinition`, `GetDefaultColumnDefinitionsForType(...)` is limited to doubles, integers, dates, and string types. You can certainly write those out manually using the same model, `ColumnDefinition` to get the behavior you're after, or even use your own class since it's just interpreted as JSON adhering to their definition client-side.

**Comment by GhostA08** [comment]
Thanks.  I was already writing out the properties instead of using the GetDefaultColumnDefinitionsForType(...) method.  I just needed to modify the type for the Values field in the ColumnDefinition class from string to object to allow for a string[] so that when I convert it to JSON it get pick up correctly on the client-side.

**Comment by tghamm** [comment]
@GhostA08 thanks for the followup.  I should probably change `Values` to an object, we'll work on that for the next release.  Thanks!
